version: "3.7"
services:
  php:
    user: ${USER_GROUP}
    build:
      context: .
      target: development-env-stage
      dockerfile: Dockerfile
    image: mphp
    volumes:
      - ${LOCAL_PROJECT_PATH}:/var/www/html
    ports:
      - ${PROJECT_PORT_MAP}
    links:
      - database:database

  database:
    image: mysql
    volumes:
      - ${LOCAL_PROJECT_PATH}/config/database/db-data:/etc/mysql/conf.d
    ports:
      - ${DATABASE_PORT_MAP}
    environment:
      - MYSQL_ROOT_PASSWORD=root
    security_opt:
      - seccomp:unconfined